# ==============================================================================
# MedGuide Backend - Development Profile Configuration
# ==============================================================================

logging:
  level:
    root: INFO
    com.medguide: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.flywaydb: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

spring:
  jpa:
    show-sql: true
